name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install codeclimate-test-reporter

      - name: Run linter
        run: |
          flake8 hexlet_code/

      - name: Run tests with coverage
        run: |
          pytest --cov=hexlet_code tests/ --cov-report=lcov > coverage.info

      - name: Upload coverage to CodeClimate
        env:
          CODECLIMATE_REPO_TOKEN: ${{ secrets.CODECLIMATE_REPO_TOKEN }}
        run: |
          codeclimate-test-reporter upload-coverage coverage.info